stages:
  - build

build/testing:
  stage: build
  tags:
    - dc/crm-dev-api
  script:
    - sudo docker-compose -f docker-compose-testing.yml up -d --build
  only:
    #- develop

build/staging:
  stage: build
  tags:
    - dc/crm-stg-api
  script:
    - sudo docker-compose -f docker-compose-staging.yml up -d --build
  only:
    #- master
