stages:
  - build

build/testing:
  stage: build
  tags:
    - dc/crm-test-api
  environment:
    name: testing
    url: https://api.test.mapp.vn/
  script:
    - ifconfig ens160
    - cp /home/slz-admin/.ssh/id_rsa .
    - sudo docker-compose -f docker/docker-compose-crm-testing.yml up --build -d
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:testing
    - sudo docker-compose build
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:latest
  only:
    - develop

build/staging:
  stage: build
  tags:
    - dc/crm-stg-api
  environment:
    name: staging
    url: https://api.stg.mapp.vn/
  script:
    - ifconfig ens160
    - cp /home/slz-admin/.ssh/id_rsa .
    - sudo docker-compose -f docker/docker-compose-staging.yml up --build -d
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:staging
    - sudo docker-compose -f docker/docker-compose-production.yml build
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:production
  only:
    - staging

build/production:
  stage: build
  tags:
    - dc/crm-prd-api
  environment:
    name: production
    url: https://api.mapp.vn/
  when: manual
  script:
    - ifconfig ens160
    - cp /home/slz-admin/.ssh/id_rsa .
    - sudo docker-compose -f docker/docker-compose-production.yml up --build -d
  only:
    - release
