stages:
  - build

build/testing:
  stage: build
  tags:
    - dc/crm-dev-api
  script:
    - ifconfig ens160
    - cp /home/slz-admin/.ssh/id_rsa .
    - sudo docker-compose -f docker/docker-compose-crm-testing.yml up --build -d
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:testing
    - sudo docker-compose build
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:latest
  only:
    - develop

build/staging:
  stage: build
  tags:
    - dc/crm-stg-api
  script:
    - ifconfig ens160
    - cp /home/slz-admin/.ssh/id_rsa .
    - sudo docker-compose -f docker/docker-compose-staging.yml up --build -d
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:staging
    - sudo docker-compose -f docker/docker-compose-production.yml build
    - sudo docker push registry.solazu.net/enterprise/saas-backend-core/service-core:production
  only:
    - master
