version: "3.7"

services:
  api:
    build:
      context: .
    image: service-core-api
    env_file: docker-compose.env
    ports:
      - "3009:3000"
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
      - auth
      - org
      - user
    depends_on:
      - nats
      - auth
      - org
      - user
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  auth:
    build:
      context: .
    image: service-core-auth
    env_file: docker-compose.env
    environment:
      SERVICES: auth
    links:
      - nats
    depends_on:
      - nats

  org:
    build:
      context: .
    image: service-core-org
    env_file: docker-compose.env
    environment:
      SERVICES: org
    links:
      - nats
    depends_on:
      - nats

  user:
    build:
      context: .
    image: service-core-user
    env_file: docker-compose.env
    environment:
      SERVICES: user
    links:
      - nats
    depends_on:
      - nats


  nats:
    image: nats

  redis:
    image: redis:alpine

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
