version: "3.7"

services:
  postgresdocker:
    image: postgres:11-alpine
    container_name: db-postgresql
    restart: always
    env_file: .env.development
    environment:
      - POSTGRES_PASSWORD=anything
    ports:
      - "5431:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data:cached

  nats:
    image: nats
    ports:
     - "4222:4222"
  redis:
    image: redis:alpine
    ports:
      - "6378:6379"
