version: "3.7"

services:
  service-core:
    build:
      context: ./../
    container_name: crm-service-core-production
    image: registry.solazu.net/enterprise/saas-backend-core/service-core:production
    env_file: ./../envs/.env.production
    restart: always
    ports:
      - "3005:3009"
    environment:
      PORT: 3009
    links:
      - crm-nats
    depends_on:
      - crm-nats
    volumes:
      - /localsrc/uploads-data-v2:/app/public/uploads

  crm-nats:
    image: nats
    container_name: crm-nats-production
    ports:
      - "4226:4222"

  crm-redis:
    image: redis:alpine
    container_name: crm-redis-production
    ports:
      - "6382:6379"
