version: "3.7"

services:
  service-core:
    build:
      context: ./../
    container_name: service-core-crm
    image: registry.solazu.net/enterprise/saas-backend-core/service-core:testing
    env_file: ./../envs/.env.testing
    restart: always
    ports:
      - "3005:3009"
      - "3007:3007"
    environment:
      PORT: 3009
    links:
      - crm-nats
    depends_on:
      - crm-nats
    volumes:
      - /localsrc/uploads-data-v2:/app/public/uploads

  crm-nats:
    image: nats
    container_name: crm-nats
    restart: always
    ports:
      - "4224:4222"

  crm-redis:
    image: redis:alpine
    container_name: crm-redis
    restart: always
    ports:
      - "6380:6379"
