version: "3.7"

services:
  api-core:
    image: dockerhub/...
    container_name: postgresdocker
    restart: always
    env_file: ./../envs/.env.development
    environment:
      - POSTGRES_PASSWORD=anything
      - POSTGRES_INITDB_ARGS=--auth-host=trust --auth-local=trust
    ports:
      - "5431:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  nats:
    image: nats
    ports:
     - "4222:4222"
  redis:
    image: redis:alpine
    ports:
      - "6378:6379"
